INSERT INTO masterdrinks VALUES
('Dark Chocolate','coffee','staple','0'),
('Cinamon Dolce','coffee','staple','1'),
('Vanilla','coffee','staple','2'),
('Pumpkin','coffee ','staple','3'),
('White Chocolate','Cofee','staple','4'),
('Hazelnut','coffee','staple','5'),
('Copper Moon','coffee','staple','6'),
('Blackberry','coffee','seasonal','7'),
('Latte Machiato','coffee','seasonal','8'),
('Salted Caramel','coffee',' taple','31'),
('Hazelnut','coffee','staple','32'),
('Dark Chocolate','coffee','staple','33'),
('Caffe',' coffee','staple','34'),
('Iced Skinny','coffee','staple','35'),
('White Chocolate','coffee','staple','36'),
('Salted Caramel','coffee','staple','37'),
('White Chocolate',' coffee','staple','38'),
('Dillon',' coffee','staple','39'),
('German Dark Chocolate','coffee','seasonal','40'),
('Salted Caramel','coffee','staple','61'),
('Hazelnut','coffee','staple','62'),
('Old Fashion',' coffee','staple','63'),
('Banana Peanut','coffee','staple','64'),
('Copper Moon','coffee','staple','65'),
('Mint','coffee','staple','66'),
('Brown Sugar','coffee','staple','67'),
('Trump','coffee','seasonal','68'),
('Strawberry','smoothie','staple','91'),
('Kiwi','smoothie','staple','92'),
('Blueberry','smoothie','staple','93'),
('Mango','smoothie','staple','94'),
('Pineapple','smoothie','staple','95'),
('Banana','smoothie','staple','96'),
('Blackberry','tea','staple','121'),
('Sweet and Sour','tea','staple','122'),
('Chai','tea','staple','123'),
('Black','tea','staple','124'),
('Green','tea','staple','125'),
('Vanilla','icecream','staple','151'),
('Dark Chocolate','icecream','staple','152');
